services:
  # ==============================================================================
  # DynamoDB Local
  # ==============================================================================
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"

    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"

    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

    hostname: dynamodb-local

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 5s
      timeout: 3s
      retries: 3

  # ==============================================================================
  # LocalStack
  # ==============================================================================
  localstack:
    image: localstack/localstack:4.14.0
    container_name: localstack

    ports:
      - "4566:4566"

    extra_hosts:
    - "host.docker.internal:host-gateway"

    # Permite que o LocalStack acesse o Docker Engine
    # para executar as Lambdas.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      # Serviços AWS utilizados pelo projeto
      - SERVICES=apigateway,events,sqs,dynamodb,logs,iam,lambda

      # Logs detalhados para diagnóstico
      - DEBUG=1

      # Credenciais locais
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

      # Docker Engine
      - DOCKER_HOST=unix:///var/run/docker.sock

      # Tempo máximo para inicialização do ambiente Lambda
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=60

      # Reutiliza o container da Lambda entre invocações
      - LAMBDA_EXECUTOR=docker-reuse

    hostname: localstack

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:4566/_localstack/health"
        ]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  default:
    name: pod99-network