server.port=8082
spring.application.name=limits-service

# AWS LocalStack
aws.dynamodb.endpoint=http://localhost:4566
aws.eventbridge.endpoint=http://localhost:4566
aws.region=us-east-1
aws.credentials.access-key-id=test
aws.credentials.secret-access-key=test
