server.port=8083
spring.application.name=accounting-service

# AWS LocalStack
aws.dynamodb.endpoint=http://localhost:4566
aws.eventbridge.endpoint=http://localhost:4566
aws.region=us-east-1
aws.credentials.access-key-id=test
aws.credentials.secret-access-key=test

# SQS
spring.cloud.aws.sqs.endpoint=http://localhost:4566
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test
spring.cloud.aws.region.static=us-east-1
